### ISSUE TITLE
同一个请求发送多次

### ISSUE THREAD

**Issue by zWingz** [shuiRong/VueCnodeJS#1]
![image](https://cloud.githubusercontent.com/assets/13031838/25470738/43018f62-2b56-11e7-94ae-2bbd1d09d116.png)
多次进入详情返回.可以看到有多个相同的请求

**Comment by shuiRong** [comment]
在此之前！关于兄弟组件之间可以共享的数据，我并没有进行选择共享，而是再次发送请求获取数据．所以造成了同一个路由下，发送了两次相同的xhr．（写代码时考虑到数据少．没想多，不过还是该处理掉想同请求的）
已改：因为数据量少，没必要用weex．就让父实例做为两个兄弟组件的中间人来传递数据．

然后我多次进入详情返回，没有发现多次请求相同资源的问题．（改之前也只是有两次相同请求）（你这种情况我不知道怎么回事...）
![github2](https://cloud.githubusercontent.com/assets/16076993/25481130/655b70d6-2b11-11e7-9292-6bdb15c3e6fe.png)
