### ISSUE TITLE
关于打包部署的问题

### ISSUE THREAD

**Issue by zhang122622623** [shuiRong/VueCnodeJS#10]
请教一下，你这个项目完成后的预览是怎么实现的？你自己申请的域名放上去的吗？
    我将打包后的dist文件夹放到github pages上，静态文件正常加载，但会出现请求跨域的问题，，
     网上说使用nginx做反向代理，这应该只针对本地查看吧？如果要在github上做类似的预览效果，该怎么实现呢？
   预览地址：https://zhang122622623.github.io/vueCnode
   源码地址：https://github.com/zhang122622623/vueCnode

**Comment by shuiRong** [comment]
![image](https://user-images.githubusercontent.com/16076993/34156686-3ee0508c-e4f9-11e7-936d-a08ed5600e7f.png)
我看了下你首页请求的API（上图），并没有看到出现跨域问题。
而这个请求404是因为你请求地址不对！ 前缀错了，应该换成cnodejs社区的，而不是你项目的地址
[https://cnodejs.org/api](看这里，最上面)

**Comment by shuiRong** [comment]
部署方面，我的确就是把dist文件夹扔到了Web服务器上了，netlify,github page, 自己服务器上，都可。

**Comment by zhang122622623** [comment]
你说请求的地址不对，意思是生产模式下请求地址也需要自己配置吗？类似开发模式在index.js中进行配置？

**Comment by zhang122622623** [comment]
确实是请求地址错了，，给生产模式也配置一个地址就可以了；多谢大佬！
