### ISSUE TITLE
运行项目时报错，cantnot find module get-iterator

### ISSUE THREAD

**Issue by maginpadding** [shuiRong/VueCnodeJS#11]
![error](https://user-images.githubusercontent.com/21351012/36650050-11fa48ac-1adc-11e8-86c2-eae4559d5c03.png)
![run_error](https://user-images.githubusercontent.com/21351012/36650061-236b40be-1adc-11e8-953f-01a9576cb21e.png)
我尝试重新npm install，但是没有用

**Comment by shuiRong** [comment]
（我刚重新clone测试了下，没有发现问题，OSX平台，所以不是package.json文件里没有这个模块的问题）
那就是安装时出了问题：使用npm需要翻墙（某些资源在国外），或者你使用cnpm。
总而言之，这种问题除了删除当前node_modules文件夹多下载几次外，没有好的办法

**Comment by maginpadding** [comment]
谢谢，我挂vpn试一下
