### ISSUE TITLE
这个什么地方式 seo 了呢,我感觉页没变啊

### ISSUE THREAD

**Issue by renyuns** [shuiRong/VueCnodeJS#13]
这个什么地方式 seo 了呢,我感觉页没变啊, title 设么的

**Comment by shuiRong** [comment]
首先，代码在[nuxtVersion文件下](https://github.com/shuiRong/VueCnodeJS/tree/master/nuxtVersion)，不要看错地方了。

“利于SEO”意味着：页面上的数据会反映在`html`文件中，可以被搜索引擎的爬虫爬到。（最简单的确认方式就是通过`右键-->显示网页源代码`查看）
