### ISSUE TITLE
请问关于nuxt.js版本的问题

### ISSUE THREAD

**Issue by cyanbluezyx** [shuiRong/VueCnodeJS#14]
在本地运行后发现服务器端渲染出来的资源里，有这么一段
`window.__NUXT__={"layout":"default","data":[{"articleListsData":[{"id":"5c2edce13898674067a7b103","author_id":"5372465f3c72496d41009adc","tab":"share","content":"截止1 月 12日晚 22:00，有效参与人数共 252 人，抽取 5 名中奖者。\r\n恭喜以下中奖者🎉🎉🎉🎉🎉 gofromzero,MoeXian,yxcs,caoxiaoshuai1,langjy🎉🎉🎉🎉🎉\r\n请评论区留下联系方式。\r\n![image.png](\u002F\u002Fstatic.cnodejs.org\u002FFvx9s9EjQk7IwNrAMO5_y7zJfrej)\r\n\r\n---------------- 以下是原文 。。。`
但是在https://mystifying-hoover-fff38f.netlify.com/这个线上demo中却没有
而我自己的项目发布到线上后也有这么一段很长的javascript，请问不显示这个需要做一些什么设置吗

**Comment by shuiRong** [comment]
> 在本地运行后发现服务器端渲染出来的资源里，有这么一段
> `window.__NUXT__={"layout":"default","data":[{"articleListsData":[{"id":"5c2edce13898674067a7b103","author_id":"5372465f3c72496d41009adc","tab":"share","content":"截止1 月 12日晚 22:00，有效参与人数共 252 人，抽取 5 名中奖者。\r\n恭喜以下中奖者🎉🎉🎉🎉🎉 gofromzero,MoeXian,yxcs,caoxiaoshuai1,langjy🎉🎉🎉🎉🎉\r\n请评论区留下联系方式。\r\n![image.png](\u002F\u002Fstatic.cnodejs.org\u002FFvx9s9EjQk7IwNrAMO5_y7zJfrej)\r\n\r\n---------------- 以下是原文 。。。`
> 但是在[https://mystifying-hoover-fff38f.netlify.com/这个线上demo中却没有](https://mystifying-hoover-fff38f.netlify.com/%E8%BF%99%E4%B8%AA%E7%BA%BF%E4%B8%8Ademo%E4%B8%AD%E5%8D%B4%E6%B2%A1%E6%9C%89)
> 而我自己的项目发布到线上后也有这么一段很长的javascript，请问不显示这个需要做一些什么设置吗

有这些东西对于Nuxt.js来说是正常的，这部分数据会[被Vue用到](https://github.com/nuxt/nuxt.js/issues/644#issuecomment-298888073)
（那个线上DEMO地址，我放错了，它是普通的Vue SPA项目DEMO而不是Nuxt.js的DEMO，晚会儿我会把链接移除）。

https://github.com/nuxt/nuxt.js/issues/644#issuecomment-298888073
