### ISSUE TITLE
接口请求401

### ISSUE THREAD

**Issue by bao15284212834** [shuiRong/VueCnodeJS#17]
请求接口成了401，咋回事呢

**Comment by shuiRong** [comment]
我看了下没复现，可能是 cnodejs.org 抽风了。

你那边浏览器单独访问：[https://cnodejs.org/api/v1/topic/5433d5e4e737cbe96dcef312](https://cnodejs.org/api/v1/topic/5433d5e4e737cbe96dcef312) 呢

**Comment by bao15284212834** [comment]
> 我看了下没复现，可能是cnodejs.org抽风了。
> 
> 你那边浏览器单独访问：[https](https://cnodejs.org/api/v1/topic/5433d5e4e737cbe96dcef312) ://cnodejs.org/api/v1/topic/5433d5e4e737cbe96dcef312呢

直接访问可以

**Comment by bao15284212834** [comment]
> 我看了下没复现，可能是 cnodejs.org 抽风了。
> 
> 你那边浏览器单独访问：https://cnodejs.org/api/v1/topic/5433d5e4e737cbe96dcef312 呢

接口返回的是错误的accesstooken

**Comment by shuiRong** [comment]
那就不晓得了。我找了个朋友看链接，也能访问...不知道你那边为什么这么特殊

**Comment by gaojing541** [comment]
可以访问+1




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "林水溶"<notifications@github.com&gt;; 
发送时间: 2021年3月2日(星期二) 下午5:11
收件人: "shuiRong/VueCnodeJS"<VueCnodeJS@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [shuiRong/VueCnodeJS] 接口请求401 (#17)





 
那就不晓得了。我找了个朋友看链接，也能访问...不知道你那边为什么这么特殊

**Comment by bao15284212834** [comment]
> 那就不晓得了。我找了个朋友看链接，也能访问...不知道你那边为什么这么特殊

终于知道哪有问题了，原来是get请求，我写成post了
