### ISSUE TITLE
run 的时候有个错误，可以帮忙看看吗！小白一个

### ISSUE THREAD

**Issue by carlstudent** [shuiRong/VueCnodeJS#2]
> vue@1.0.0 dev F:\vue\demo\VueCnodeJS
> node build/dev-server.js

> Starting dev server...
 ERROR  Failed to compile with 8 errors14:51:38

 error  in ./src/main.js

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  F:\vue\demo\VueCnodeJS\src\main.js:1:59
  // The Vue build version to load with the `import` command
                                                             ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  F:\vue\demo\VueCnodeJS\src\main.js:2:81
  // (runtime-only or standalone) has been set in webpack.base.conf with an alias.
                                                                                   ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  F:\vue\demo\VueCnodeJS\src\main.js:3:23
  import Vue from 'vue';
                         ^

  ✘  https://google.com/#q=import%2Fextensions     Unexpected use of file extension "vue" for "vue-svg-icon/Icon.vue"
  F:\vue\demo\VueCnodeJS\src\main.js:4:18
  import Icon from 'vue-svg-icon/Icon.vue';

**Comment by shuiRong** [comment]
这是eslint报的错．
eslint是什么？
一个规范代码的东西，强制你写出符合规范的代码，否则报错．
删掉根文件夹的.eslintrc.js，就会让eslint失效．就能build了．
关掉它有什么坏处？
没什么坏处．规范代码嘛，新手先不用管它
