### ISSUE TITLE
关于v-for

### ISSUE THREAD

**Issue by SweetyWei** [shuiRong/VueCnodeJS#4]
v-for = "item in content"．
作者果然很贴心，已点star,在MainSec组件中v-for指令有一点点小瑕疵．

**Comment by shuiRong** [comment]
我猜是 少了:key 然后Vue Warn 了吧.
(晚会儿就改掉,我记得当初写项目时Vue好像还没有出这些警告.)

**Comment by guaizi149** [comment]
非常好，一个个commit看过来的。lz么么哒~

**Comment by shuiRong** [comment]
性别男,
完结,撒花.
