### ISSUE TITLE
刚看完VUe2.x基础篇，对组件后面杂项部分很迷茫啊

### ISSUE THREAD

**Issue by oroz-vip** [shuiRong/VueCnodeJS#7]
看到杂项里面的异步子组件和高级异步子组件，看不懂了，偶然看到了hub主的这个实战，感觉我要能写出来，还是遥遥无期。想请教一下，在学Vue之前是不是需要先学会node.js 和 webpack这些吖

**Comment by shuiRong** [comment]
不需要专门去学Node和Webpack相关知识（但遇到问题了，基本的Google还是要会的）
而且这个项目本来就是新手向的，根本没有用到异步组件的知识。（当然，如果你以后想优化的话，可以尝试这些概念）。
总而言之，看完文档基础篇，完全可以上手写这个项目了。（完全自己写，或者跟着我的Commit写都可以）

加油啊，少年！
