### ISSUE TITLE
favico去哪里了

### ISSUE THREAD

**Issue by Virczz** [shuiRong/VueCnodeJS#8]
提一个小白问题，我发现你在代码里面，没有任何地方写了favico。但是在跑你的代码的时候，会在标签栏哪里有图标。怎么做到的？

**Comment by shuiRong** [comment]
这个是在index.html页里指定的，图标文件放在staticw文件夹下哦。

![image](https://user-images.githubusercontent.com/16076993/33982728-89284016-e0ec-11e7-84d2-e7d917b8e37c.png)

在这个地方可以检索当前仓库的代码。

**Comment by Virczz** [comment]
我....我按照你在知乎上说的一个个commit的来学，我学到你添加axio的地方，突然发现你的代码里面没有favico，但是标签上有。现在看了你的回复，去看log，才发现，你也是在后面才加的图标 :(

**Comment by shuiRong** [comment]
当初的确是做到后面才想起来加图标，哈哈
