### ISSUE TITLE
在第二次进入详情页的时候，SideCom组件会一直loading

### ISSUE THREAD

**Issue by Virczz** [shuiRong/VueCnodeJS#9]
没错，又是我这个渣新。虽然我已经看了一遍vue.js，但还不能自如运用。。请指教这个bug的修改思路。

**Comment by shuiRong** [comment]
:) 你可以先看看Vue的声明周期，感觉这块儿的问题（白天忙，晚上有空看看怎么回事儿）

**Comment by cw84973570** [comment]
@Virczz 因为第二次进入详情页的时候App组件并没有重载，App组件的authorName属性和article组件传递过来的数据是相等的，所以App中的watch钩子不会执行，那么自然sideSec中的wathc钩子也不会执行了，所以没有请求数据一直在loading。
实际上不需要把数据传递给父组件再传递给另一个子组件这么麻烦，而且vue文档也不提倡使用$parent通信，直接使用$emit和$on在兄弟组件中通信就好了。http://blog.csdn.net/panyang01/article/details/76222713 随便找了篇兄弟组件通信的文章
学习了一段时间发现作者的代码有不少需要优化的地方，不过还是一个很好的供学习的demo，已star，感谢。

**Comment by shuiRong** [comment]
加了个created回调，解决掉了。（拖得挺久...）

> PS: 顺便看了看项目，呃，完全可以重构，优化的更好...
